#!/bin/bash --

MY_DIR=`dirname $0`
source $MY_DIR/../../SetEnv

echo "HC: Ensure there are not NOT GO annotations in the BioMart"

sql="select * from object_xref join xref on (object_xref.xref_id=xref.xref_id) join external_db on (xref.external_db_id=external_db.external_db_id) join ${DBMARTNAME}.spombe_eg_gene__ox_go__dm on (spombe_eg_gene__ox_go__dm.transcript_id_1064_key=object_xref.ensembl_id and spombe_eg_gene__ox_go__dm.dbprimary_acc_1074=xref.dbprimary_acc) where external_db.db_name='GO' and object_xref.ensembl_object_type='Transcript' and object_xref.linkage_annotation='NOT';"
sqlCount="select count(*) from object_xref join xref on (object_xref.xref_id=xref.xref_id) join external_db on (xref.external_db_id=external_db.external_db_id) join ${DBMARTNAME}.spombe_eg_gene__ox_go__dm on (spombe_eg_gene__ox_go__dm.transcript_id_1064_key=object_xref.ensembl_id and spombe_eg_gene__ox_go__dm.dbprimary_acc_1074=xref.dbprimary_acc) where external_db.db_name='GO' and object_xref.ensembl_object_type='Transcript' and object_xref.linkage_annotation='NOT';"

c=`mysql -u$DBUSER -p$DBPASS -h$DBHOST -P$DBPORT $DBCORENAME -N -e "${sql}"`

if [ ${#c} -gt 0 ]
then
  echo "  FAILED"
  echo "  There are NOT annotations present in the BioMart ox tables"
  echo "  Check the SQL generated by BioMart."
  echo ""
  echo "  RESULTS"
  echo "  ${sqlCount}"
  mysql -u$DBUSER -p$DBPASS -h$DBHOST -P$DBPORT $DBCORENAME -e "${sqlCount}"
  echo ""
  echo "  REASON"
  echo "  There are links in the martbuilder that have not been set to filter out the NOT annotations."
else
  echo "PASSED"
fi

sql="select * from object_xref join xref on (object_xref.xref_id=xref.xref_id) join external_db on (xref.external_db_id=external_db.external_db_id) join ${DBMARTNAME}.spombe_eg_gene__ontology_go__dm on (spombe_eg_gene__ontology_go__dm.transcript_id_1064_key=object_xref.ensembl_id and spombe_eg_gene__ontology_go__dm.dbprimary_acc_1074=xref.dbprimary_acc) where external_db.db_name='GO' and object_xref.ensembl_object_type='Transcript' and object_xref.linkage_annotation='NOT';"
sqlCount="select count(*) from object_xref join xref on (object_xref.xref_id=xref.xref_id) join external_db on (xref.external_db_id=external_db.external_db_id) join ${DBMARTNAME}.spombe_eg_gene__ontology_go__dm on (spombe_eg_gene__ontology_go__dm.transcript_id_1064_key=object_xref.ensembl_id and spombe_eg_gene__ontology_go__dm.dbprimary_acc_1074=xref.dbprimary_acc) where external_db.db_name='GO' and object_xref.ensembl_object_type='Transcript' and object_xref.linkage_annotation='NOT';"

c=`mysql -u$DBUSER -p$DBPASS -h$DBHOST -P$DBPORT $DBCORENAME -N -e "${sql}"`

if [ ${#c} -gt 0 ]
then
  echo "  FAILED"
  echo "  There are NOT annotations present in the BioMart ontology tables"
  echo "  Check the SQL generated by BioMart."
  echo ""
  echo "  RESULTS"
  echo "  ${sqlCount}"
  mysql -u$DBUSER -p$DBPASS -h$DBHOST -P$DBPORT $DBCORENAME -e "${sqlCount}"
  echo ""
  echo "  REASON"
  echo "  There are links in the martbuilder that have not been set to filter out the NOT annotations."
else
  echo "PASSED"
fi
