#!/bin/bash --

MY_DIR=`dirname $0`
source $MY_DIR/../SetEnv

mkdir -p ../data/FTP
cd ../data/FTP

mysql -u$DBUSER -p$DBPASS -h$DBHOST -P$DBPORT $DBCORENAME -N -e "SELECT m.stable_id FROM ( SELECT gt.stable_id, SUM( IF(t.accession is null, 0, 1) ) AS mCount FROM ( SELECT gene.stable_id, xref.dbprimary_acc FROM gene JOIN transcript ON (gene.gene_id=transcript.gene_id) JOIN object_xref ON (transcript.transcript_id=object_xref.ensembl_id) JOIN xref ON (object_xref.xref_id=xref.xref_id) JOIN external_db ON (xref.external_db_id=external_db.external_db_id) JOIN ${DBNAME}.term child ON (child.accession=xref.dbprimary_acc) JOIN ${DBNAME}.closure ON (child.term_id=closure.child_term_id) JOIN ${DBNAME}.term parent ON (closure.parent_term_id=parent.term_id) WHERE external_db.db_name='GO' AND object_xref.ensembl_object_type='Transcript' AND parent.accession='GO:0008150' AND gene.biotype='protein_coding' ) AS gt LEFT JOIN ( SELECT DISTINCT child.accession FROM ${DBNAME}.term parent JOIN ${DBNAME}.aux_GO_goslim_pombe_map ON (parent.term_id=aux_GO_goslim_pombe_map.subset_term_id) JOIN ${DBNAME}.closure ON (parent.term_id=closure.parent_term_id) JOIN ${DBNAME}.term child ON (closure.child_term_id=child.term_id) WHERE parent.name NOT IN ('biological_process', 'molecular_function', 'cellular_compartment') ) AS t ON (gt.dbprimary_acc=t.accession) GROUP BY gt.stable_id ) AS m WHERE m.mCount=0;" > GOSlimExceptions.tsv

mysql -u$DBUSER -p$DBPASS -h$DBHOST -P$DBPORT $DBCORENAME -N -e "SELECT m.stable_id FROM ( SELECT gene.stable_id, SUM(IF(parent.name='biological_process',1,0)) AS bp, SUM(IF(parent.name='molecular_function',1,0)) AS mf, SUM(IF(parent.name='cellular_component',1,0)) AS cc FROM gene JOIN transcript ON (gene.gene_id=transcript.gene_id) LEFT JOIN object_xref ON (transcript.transcript_id=object_xref.ensembl_id) LEFT JOIN xref ON (object_xref.xref_id=xref.xref_id) LEFT JOIN external_db ON (xref.external_db_id=external_db.external_db_id) LEFT JOIN ${DBNAME}.term child ON (child.accession=xref.dbprimary_acc) LEFT JOIN ${DBNAME}.closure ON (child.term_id=closure.child_term_id) LEFT JOIN ${DBNAME}.term parent ON (closure.parent_term_id=parent.term_id) WHERE external_db.db_name='GO' AND object_xref.ensembl_object_type='Transcript' AND gene.biotype='protein_coding' GROUP BY gene.stable_id ) AS m WHERE m.bp=0 AND ( m.mf>0 OR m.cc>0 );" > GOSlimExceptionsAll.tsv
